#ifndef LPMODEL_TYPES_H
#define LPMODEL_TYPES_H

namespace LPModel
{
    enum LinearizationLevel{LINEARIZATION_NONE=0,LINEARIZATION_PIXEL_PAIR=1,LINEARIZATION_PIXEL_LINEL=2,LINEARIZATION_ALL_COUPLED=3,LINEARIZATION_ALL_UNCOUPLED=4};
    enum RelaxationLevel{RELAXATION_NONE=0,RELAXATION_ORIGINAL=1,RELAXATION_AUXILIAR=2,RELAXATION_ALL=3};
}

#endif //LPMODEL_TYPES_H
