IMAGE_NAME=$1
GRID_STEP=$2
LEVELS=$3
SQ_WEIGHT=$4
DATA_WEIGHT=$5

ROOT_PROJECT_FOLDER=/home-local/dantu1/GIT/PhD/LPModel
BIN_FOLDER=$ROOT_PROJECT_FOLDER/cmake-build-debug
SCRIPT_FOLDER=$ROOT_PROJECT_FOLDER/lp-solve-scripts

if [ -z $6 ]
then
    OUTPUT_FOLDER=$ROOT_PROJECT_FOLDER/output/$IMAGE_NAME/h$GRID_STEP
else
    OUTPUT_FOLDER=$6
fi


INPUT_IMAGES=$ROOT_PROJECT_FOLDER/input-images
mkdir -p $INPUT_IMAGES


mkdir -p $OUTPUT_FOLDER



$BIN_FOLDER/generate-initial-shapes $INPUT_IMAGES $GRID_STEP


$BIN_FOLDER/export-lp $INPUT_IMAGES/$IMAGE_NAME.pgm $LEVELS $SQ_WEIGHT $DATA_WEIGHT $OUTPUT_FOLDER
gurobi_cl Method=1 ResultFile=$OUTPUT_FOLDER/${IMAGE_NAME}.sol $OUTPUT_FOLDER/${IMAGE_NAME}.lp

$BIN_FOLDER/generate-solution $OUTPUT_FOLDER/prm.pgm $LEVELS $OUTPUT_FOLDER/grid.obj $OUTPUT_FOLDER/${IMAGE_NAME}.sol $OUTPUT_FOLDER/solution.pgm
